# Site settings
name: Esporo
tagline: A comunidade brasileira de Spore.
description: Comunidade online de Spore e Darkspore com notícias, tutoriais, guias, fórum de discussão e downloads para seu jogo.
email: contato@esporo.net

lang: pt-br
encoding: utf-8
timezone: "America/Sao_Paulo"

url: "https://esporo.net"
baseurl: ""

# SEO settings
twitter:
  username: esporo

logo: "/assets/images/logo.jpg"

social:
  name: Esporo
  links:
    - "https://www.facebook.com/esporo"
    - "https://twitter.com/esporo"
    - "https://youtube.com/esporotv"
    - "https://plus.google.com/+esporonet"

google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

# Build settings
source: _source
destination: _site

permalink: "/noticias/post/:year/:title/"
pagination:
  enabled: true
  collection: "posts"
  per_page: 5
  sort_reverse: true
  permalink: "/arquivo/parte/:num/"
  title: ":title <span>(parte :num de :max)</span>"

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - "archive.html"
    title: "Posts sobre <b>:tag</b>"
    permalink: "/noticias/tag/:tag/"
    slugify:
      mode: "raw"
      cased: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: arthur

collections:
  games:
    output: true
    permalink:  "/jogos/:name/"
  svg:
    output: false

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-coffeescript
