# Site Settings
title: Esporo
tagline: A comunidade brasileira de Spore
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"

lang: pt-BR
timezone: "America/Sao_Paulo"

email: contato@esporo.net
url: "https://esporo.net"
baseurl: ""

# Content settings
theme: jekyll-theme-charlie

charlie:
  hide_site_title: true
  date_formats:
    day: "%d/%m/%Y"
    month: "%m/%Y"
    year: "%Y"

# Build settings
incremental: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "gaboo"

plugins:
  - jekyll-octicons

# Build Settings
permalink: "/:year/:month/:title/"

keep_files:
  - favicon.ico
  - uploads
  - assets/fonts
  - assets/icons
  - assets/images
  - assets/js

# Plugin: jekyll-seo-tag
google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - https://twitter.com/esporo
    - https://www.youtube.com/user/esporotv
    - https://www.facebook.com/esporo

# Plugin: jekyll-archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: "archive"
  slug_mode: default
  permalinks:
    tag: "/tags/:name/"
    year: "/:year/"
    month: "/:year/:month/"
