# Site Settings
title: Esporo
tagline: A comunidade brasileira de Spore.
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"

lang: pt-BR
timezone: "America/Sao_Paulo"

email: spark@esporo.net
url: "https://esporo.net"
baseurl: ""

spark:
  date_format:
    day: "%d de %B de %Y"
    month: "%B de %Y"
    year: "%Y"
  directories:
    posts: "/noticias/"
    games: "/jogos/"
  disclaimer: >-
    &copy; 2005 – 2019 Esporo.
    O Esporo não é um site oficial. Spore e Maxis são marcas proprietárias da Electronic Arts.
  comments: false
  comments_notice: >-
    1. Campos marcados com (*) são obrigatórios.
    2. Seu email não será exibido ou guardado.
    3. Você pode [usar Markdown](https://forum.esporo.net/d/3-formatando-seu-post) para formatar seu comentário.
    4. As [regras do fórum](https://forum.esporo.net/d/9-regras-do-f-rum) valem aqui também.

# Build settings
collections:
  games:
    output: true
    permalink: "/jogos/:title/"

permalink: "/:year/:month/:title/"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-octicons

social:
  name: Esporo
  links:
    - https://twitter.com/esporo
    - https://www.youtube.com/user/esporotv
    - https://www.facebook.com/esporo

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    category: "/categorias/:name/"
    tag: "/tags/:name/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "gaboo"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"

jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    layout: post
    category: Spore
    tags:
  post_default_front_matter:
    layout: post
    category: Spore
    tags:
