# Site Settings
title: Esporo
description: >-
  A comunidade brasileira de Spore.
logo: "/assets/images/logo.jpg"
  
email: contato@esporo.net
lang: pt-BR
timezone: "America/Sao_Paulo"

url: "https://esporo.net"
baseurl: ""

collections:
  games:
    output: true
    permalink: "/jogos/:title/"
    
permalink: "/noticias/post/:title/"

# Theme Settings
spark:
  custom_fonts: true # set to true to load fonts.css
  show_excerpts: false # set to true to show post excerpts, not the entire post content.
  
# SEO settings
twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - "https://twitter.com/esporo"
    - "https://www.youtube.com/user/esporotv"
    - "https://www.flickr.com/photos/esporo"
    - "https://www.facebook.com/esporo"
    
google_site_verification: "to_set"

# Collections settings
collections:
  games:
    output: true
    permalink: "/jogos/:title/"
  
franchises-order:
  - Spore
  - Darkspore
  - Consoles

games-order:
  - base
  - bundle
  - pack
  - beta


# Build settings
pagination:
  enabled: true
  collection: "posts"
  per_page: 10
  permalink: "/p/:num/"
  title: ":title (:num de :max)"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    layouts:
      - "archive.html"
    title: ":title — Arquivo de Notícias"
    permalink: "/noticias/categoria/:cat/"
    slugify:
      mode: raw
      cased: true
  tags:
    enabled: false
    layouts:
      - "archive.html"
    title: ":title — Arquivo de Notícias"
    permalink: "/noticias/tag/:tag/"
    slugify:
      mode: raw
      cased: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-octicons
  - jekyll-paginate-v2