# Site Settings
title: Esporo
tagline: A comunidade brasileira de Spore
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"

lang: pt-BR
timezone: "America/Sao_Paulo"

email: contato@esporo.net
url: "https://esporo.net"
baseurl: ""

# Content settings
spark:
  date_format:
    day: "%d de %B de %Y"
    month: "%B de %Y"
    year: "%Y"
  directories:
    posts: "/noticias/"
    games: "/jogos/"
  disclaimer: >-
    &copy; 2005 – 2019 Esporo.
    O Esporo não é um site oficial. Spore e Maxis são marcas proprietárias da Electronic Arts.
  comments: false

# Build settings
collections:
  games:
    output: true
    permalink: "/jogos/:title/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "gaboo"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"

# Build Settings
permalink: "/:year/:month/:title/"

include:
  - _pages
  - _redirects
  - _headers

keep_files:
  - uploads
  - assets/fonts
  - assets/icons
  - assets/images
  - assets/js

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-octicons
  - jekyll-include-cache
  - jekyll-admin

# SEO
adsense_property_id: "ca-pub-6140421780025442"
google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - https://twitter.com/esporo
    - https://www.youtube.com/user/esporotv
    - https://www.facebook.com/esporo

# Archives
jekyll-archives:
  enabled: all
  layout: "archive"
  permalinks:
    category: "/categorias/:name/"
    tag: "/tags/:name/"
    year: "/:year/"
    month: "/:year/:month/"
