# Site Settings
title: Esporo
tagline: A comunidade brasileira de Spore.
description: >-
  A comunidade brasileira para Spore, com conteúdos personalizados para download, fóruns de discussão e ajuda, guias de jogo e as últimas notícias.
logo: "/assets/images/logo.png"

email: contato@esporo.net
lang: pt-BR
timezone: "America/Sao_Paulo"

url: "https://esporo.net"
baseurl: ""

theme: "jekyll-theme-spark"

# Theme Settings
spark:
  date_format:
    day: "%d de %B de %Y"
    month: "%B de %Y"
    year: "%Y"
  directories:
    posts: "/noticias/"
    games: "/jogos/"
  disclaimer: >-
    O Esporo é mantido por fãs. Spore e Maxis são propriedade da Electronic Arts.
  comments: true
  comments_notice: >-
    - Campos marcados com (*) são obrigatórios.

    - Seu email não será publicado.

    - As [regras do fórum](https://forum.esporo.net/d/9-regras-do-f-rum) também se aplicam aos comentários

# SEO settings
twitter:
  card: summary
  username: esporo

social:
  name: Esporo
  links:
    - "https://twitter.com/esporo"
    - "https://www.youtube.com/user/esporotv"
    - "https://www.facebook.com/esporo"

google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

# Collections settings
collections:
  games:
    output: true
    permalink: "/jogos/:title/"

# Build settings
repository: esporo.net

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: gaboo
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"

include:
  - _md-writer
