# Site settings
name: Esporo
description: A comunidade brasileira de Spore.
email: contato@esporo.net

lang: pt-BR
encoding: utf-8
timezone: "America/Sao_Paulo"

url: "https://esporo.net"
baseurl: ""

author:
  name: Gaboo
  url: http://esporo.net/forum/members/gaboo

# Build settings
source: _source
destination: _site
include:
  - stats.php

permalink: "/noticias/:year/:title/"
pagination:
  enabled: true
  per_page: 5
  permalink: "/partes/:num/"
  title: ":title (página :num)"
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  categories:
    layouts:
      - archive.html
    title: "Posts arquivados em :cat"
    permalink: "/noticias/arquivo/categoria/:cat/"
    slugify:
      mode: pretty
      cased: true
  collections:
    enabled: false
  tags:
    layouts:
      - archive.html
    title: "Posts sobre :tag"
    permalink: "/noticias/arquivo/tag/:tag/"
    slugify:
      mode: pretty
      cased: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  games:
    output: true
    permalink:  "/jogos/:name/"
  svg:
    output: false

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
