# Site settings
name: Esporo
tagline: A comunidade brasileira de Spore.
description: Comunidade online de Spore e Darkspore com notícias, tutoriais, guias, fórum de discussão e downloads para seu jogo.
email: contato@esporo.net

lang: pt-BR
encoding: utf-8
timezone: "America/Sao_Paulo"

url: "https://esporo.net"
baseurl: ""

author:
  name: Gaboo
  url: http://esporo.net/forum/members/gaboo

# Build settings
source: _source
destination: _site

permalink: "/noticias/:year/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  games:
    output: true
    permalink:  "/jogos/:name/"
  svg:
    output: false

sass:
  style: compressed

jekyll-archives:
  enabled:
    - tags
  layout: 'archive'
  permalinks:
    tag: '/noticias/tag/:name/'

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
