# Site Settings
title: Esporo
description: >-
  A comunidade brasileira de Spore.

email: contato@esporo.net
lang: pt-BR
author: arthrfrts

# Theme Settings
spark:
  fonts: # Custom fonts should exist in `/assets/fonts/` and `/assets/css/fonts.scss`.
    body: '"Proxima Nova", system-ui, sans-serif'
    title: '"SPORE", sans-serif'
  colors:
    text: "#142533"
    brand: "#2987C7"
    accent: "#FCD704"
    details: "#A7DA78"
    background: "#FFFFFF"

# SEO Settings
twitter:
  username: esporo
  card: summary

logo: "/assets/images/logo.jpg"

social:
  name: Esporo
  links:
    - "https://twitter.com/esporo"
    - "https://www.facebook.com/esporo"
    - "https://www.youtube.com/user/esporotv"

google_site_verification: "HvEDdWfesPnf99AxWv1yVL_bZfKiGp9XYmGcVz-ZJS4"

# Content settings
collections:
  games:
    output: true
    permalink: "/jogos/:title/"
  pages:
    output: true
    permalink: "/:title/"

# Build Settings
permalink: "/noticias/post/:name/"
theme: jekyll-theme-spark

pagination:
  enabled: true
  collection: "posts"
  per_page: 5
  permalink: "/arquivo/:num/"
  title: ":title (:num de :max)"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  collections: disabled
  categories:
    layouts:
      - "archive.html"
    title: "Posts arquivados em :cat"
    permalink: "/noticias/categoria/:cat"
  tags:
    layouts:
      - archive.html
    title: "Posts marcados com :tag"
    permalink: "/noticias/tag/:tag"

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
